=== korea-doko/ReincarnationInAnotherWorld/ReincarnationProject/Assets/Resources/TextAssets/NPCActionChoiceTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="NPCActionChoiceTable" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="NPCActionChoiceTable">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="iDhXQpeLc0GKDtqe1C1p2g==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACIOFdCl4tzQYoO2p7ULWnaAAAAALwSR4lz7uRAAAAAAAAAAABOAFAA
QwBBAGMAdABpAG8AbgBDAGgAbwBpAGMAZQBUAGEAYgBsAGUAAAAAAAAAKS830OPN
PEGPf0kYR7e2agcAAACIOFdCl4tzQYoO2p7ULWnaSQBEAAAAAAAAAOlj1apy075I
hcPVL/ecQBUAAAAAQbkylnPu5EAAAAAAAAAAAE4AUABDAEEAYwB0AGkAbwBuAEMA
aABvAGkAYwBlAE4AYQBtAGUAVABhAGIAbABlAAAAAAAAAKWCLVDhYrxEvrOgZbXc
HNwHAAAA6WPVqnLTvkiFw9Uv95xAFUkARAAAAAAAAADglO8SMGANTL2xT/Vz8/70
BwAAAOlj1apy075IhcPVL/ecQBVOAFAAQwBBAGMAdABpAG8AbgBDAGgAbwBpAGMA
ZQBOAGEAbQBlAAAAAAAAANzQt8D9s9RGp/ty6ERlePoHAAAAiDhXQpeLc0GKDtqe
1C1p2k4AUABDAEEAYwB0AGkAbwBuAEMAaABvAGkAYwBlAE4AYQBtAGUAAAAAAAAA
uxGGIOcMQ0ufm/updZK97gAAAABN/zBdc+7kQAAAAAAAAAAATgBQAEMAQQBjAHQA
aQBvAG4ATgBhAG0AZQBUAGEAYgBsAGUAAAAAAAAAKn1ShVQjo0qNbiVVbxv90AcA
AAC7EYYg5wxDS5+b+6l1kr3uSQBEAAAAAAAAAHLL6k0xK8BCrxipZ7qraAAHAAAA
uxGGIOcMQ0ufm/updZK97k4AUABDAEEAYwB0AGkAbwBuAE4AYQBtAGUAAAAAAAAA
vABqu23mtkGRxcx2V79FAAcAAACIOFdCl4tzQYoO2p7ULWnaUABhAHIAZQBuAHQA
QQBjAHQAaQBvAG4ATgBhAG0AZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUA
AAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="KS830OPNPEGPf0kYR7e2ag==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="NPCActionChoiceName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="3NC3wP2z1Ean+3LoRGV4+g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2910"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [NPCActionChoiceNameTable].[ID], [NPCActionChoiceNameTable].[NPCActionChoiceName] FROM NPCActionChoiceNameTable; "/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ParentActionName" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="vABqu23mtkGRxcx2V79FAA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2340"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [NPCActionNameTable].[ID], [NPCActionNameTable].[NPCActionName] FROM NPCActionNameTable; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/ReincarnationInAnotherWorld/ReincarnationProject/Assets/Resources/TextAssets/NPCActionChoiceTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="NPCActionChoiceTable.xsd" generated="2017-05-16T14:35:31">
<NPCActionChoiceTable>
<ID>1</ID>
<NPCActionChoiceName>1</NPCActionChoiceName>
<ParentActionName>1</ParentActionName>
<Desc>힘들지만 바로 모험가 길드로 돌아간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>2</ID>
<NPCActionChoiceName>2</NPCActionChoiceName>
<ParentActionName>1</ParentActionName>
<Desc>장비의 점검이 우선이다. 대장간으로 먼저 가자.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>3</ID>
<NPCActionChoiceName>3</NPCActionChoiceName>
<ParentActionName>1</ParentActionName>
<Desc>상처 점검이 먼저다. 수도원으로 가자.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>4</ID>
<NPCActionChoiceName>4</NPCActionChoiceName>
<ParentActionName>1</ParentActionName>
<Desc>식량 보급이 우선이다. 식료품점으로 가자.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>5</ID>
<NPCActionChoiceName>5</NPCActionChoiceName>
<ParentActionName>1</ParentActionName>
<Desc>고가의 마법도구를 먼저 확인한다. 마법도구점으로 간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>6</ID>
<NPCActionChoiceName>6</NPCActionChoiceName>
<ParentActionName>1</ParentActionName>
<Desc>아직 도시 바깥에서 해야할 것을 다 하지 못했다.  숲으로 간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>7</ID>
<NPCActionChoiceName>7</NPCActionChoiceName>
<ParentActionName>1</ParentActionName>
<Desc>도시에 들어온 것을 경비대에 보고하자.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>8</ID>
<NPCActionChoiceName>8</NPCActionChoiceName>
<ParentActionName>2</ParentActionName>
<Desc>모험가 길드로 간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>9</ID>
<NPCActionChoiceName>9</NPCActionChoiceName>
<ParentActionName>2</ParentActionName>
<Desc>대장간으로 간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>10</ID>
<NPCActionChoiceName>10</NPCActionChoiceName>
<ParentActionName>2</ParentActionName>
<Desc>수도원으로 간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>11</ID>
<NPCActionChoiceName>11</NPCActionChoiceName>
<ParentActionName>2</ParentActionName>
<Desc>식료품점으로 간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>12</ID>
<NPCActionChoiceName>12</NPCActionChoiceName>
<ParentActionName>2</ParentActionName>
<Desc>마법 도구점으로 간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>13</ID>
<NPCActionChoiceName>13</NPCActionChoiceName>
<ParentActionName>2</ParentActionName>
<Desc>숲으로 간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>14</ID>
<NPCActionChoiceName>14</NPCActionChoiceName>
<ParentActionName>2</ParentActionName>
<Desc>경비대에 간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>15</ID>
<NPCActionChoiceName>15</NPCActionChoiceName>
<ParentActionName>3</ParentActionName>
<Desc>숲 속으로 들어가서 무엇이든 찾아본다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>16</ID>
<NPCActionChoiceName>16</NPCActionChoiceName>
<ParentActionName>3</ParentActionName>
<Desc>숲 속은 위험하다. 어떤 몬스터가 있을지 모른다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>17</ID>
<NPCActionChoiceName>17</NPCActionChoiceName>
<ParentActionName>3</ParentActionName>
<Desc>차라리 주변에서 사람이 있는지 찾아보자.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>18</ID>
<NPCActionChoiceName>18</NPCActionChoiceName>
<ParentActionName>4</ParentActionName>
<Desc>앞에 보이는 접수원에게 다가간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>19</ID>
<NPCActionChoiceName>19</NPCActionChoiceName>
<ParentActionName>4</ParentActionName>
<Desc>모험가 길드에서 볼 일은 없다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>20</ID>
<NPCActionChoiceName>20</NPCActionChoiceName>
<ParentActionName>5</ParentActionName>
<Desc>성당에 있는 사제에게 가본다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>21</ID>
<NPCActionChoiceName>21</NPCActionChoiceName>
<ParentActionName>5</ParentActionName>
<Desc>아직은 성당에서 볼 일은 없다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>22</ID>
<NPCActionChoiceName>22</NPCActionChoiceName>
<ParentActionName>6</ParentActionName>
<Desc>주인으로 보이는 여자에게 다가간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>23</ID>
<NPCActionChoiceName>23</NPCActionChoiceName>
<ParentActionName>6</ParentActionName>
<Desc>아직은 볼 일이 없다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>24</ID>
<NPCActionChoiceName>24</NPCActionChoiceName>
<ParentActionName>7</ParentActionName>
<Desc>앞에 보이는 마법사에게 다가간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>25</ID>
<NPCActionChoiceName>25</NPCActionChoiceName>
<ParentActionName>7</ParentActionName>
<Desc>아직은 볼 일이 없다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>26</ID>
<NPCActionChoiceName>26</NPCActionChoiceName>
<ParentActionName>9</ParentActionName>
<Desc>앞에 보이는 대장장이에게 다가간다.</Desc>
</NPCActionChoiceTable>
<NPCActionChoiceTable>
<ID>27</ID>
<NPCActionChoiceName>27</NPCActionChoiceName>
<ParentActionName>9</ParentActionName>
<Desc>아직 볼 일이 없다.</Desc>
</NPCActionChoiceTable>
</dataroot>
