=== korea-doko/ReincarnationInAnotherWorld/ReincarnationProject/Assets/Resources/TextAssets/PassiveTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="PassiveTable" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="PassiveTable">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="Ln5lfZrDSEmRynvKGnOyfg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAufmV9msNISZHKe8oac7J+AAAAAK6ekx4T8ORAAAAAAAAAAABQAGEA
cwBzAGkAdgBlAFQAYQBiAGwAZQAAAAAAAABJ9uJwdUxVRbZUNy+dp6IQBwAAAC5+
ZX2aw0hJkcp7yhpzsn5JAEQAAAAAAAAAk8lN9T+H3kyKc8mUYhGhTgAAAAAKwikj
EfDkQAAAAAAAAAAAUABhAHMAcwBpAHYAZQBOAGEAbQBlAFQAYQBiAGwAZQAAAAAA
AADHO5eQus9EQJ9o437FGpVCBwAAAJPJTfU/h95MinPJlGIRoU5JAEQAAAAAAAAA
0Mh1nO+GuE63qUbaI4aB5gcAAACTyU31P4feTIpzyZRiEaFOUABhAHMAcwBpAHYA
ZQBOAGEAbQBlAAAAAAAAAJlpQTQPfnRLmYtJzxAjIPMHAAAALn5lfZrDSEmRynvK
GnOyflAAYQBzAHMAaQB2AGUATgBhAG0AZQAAAAAAAABP4KhN/zeeQ4EW5MIQZdc3
AAAAAE+D3joR8ORAAAAAAAAAAABQAGEAcwBzAGkAdgBlAFQAeQBwAGUAVABhAGIA
bABlAAAAAAAAADg10jhb4H9Fp1yxseHE1lgHAAAAT+CoTf83nkOBFuTCEGXXN0kA
RAAAAAAAAACKokQaw89rSZRnHn26Wy/IBwAAAE/gqE3/N55DgRbkwhBl1zdQAGEA
cwBzAGkAdgBlAFQAeQBwAGUAAAAAAAAAtIhG92GpdU+yvTNoGhhC7QcAAAAufmV9
msNISZHKe8oac7J+UABhAHMAcwBpAHYAZQBUAHkAcABlAAAAAAAAAOAF6d6HaVNG
m8GIjpMgdHkHAAAALn5lfZrDSEmRynvKGnOyfkQAZQBzAGMAAAAAAAAAVtwvOED7
+kywaRskFVcLjgcAAAAufmV9msNISZHKe8oac7J+RABlAGwAdABhAEgAUAAAAAAA
AAAjCxnCYvrKTYMjcYoQtCWLBwAAAC5+ZX2aw0hJkcp7yhpzsn5EAGUAbAB0AGEA
RABhAG0AYQBnAGUAAAAAAAAAL5PK7evdjUC0j1PABLnCxgcAAAAufmV9msNISZHK
e8oac7J+RABlAGwAdABhAEQAZQBmAAAAAAAAAOv/jXmHMtVHtRVt9S50dFQHAAAA
Ln5lfZrDSEmRynvKGnOyfkQAZQBsAHQAYQBHAG8AbABkAAAAAAAAAHtKdV5yzZRA
matQTFsibkIHAAAALn5lfZrDSEmRynvKGnOyfkQAZQBsAHQAYQBIAHUAbgBnAGUA
cgAAAAAAAADcOqgmivEMTKaeCUnSZDglBwAAAC5+ZX2aw0hJkcp7yhpzsn5DAG8A
dQBuAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAA
AAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="SfbicHVMVUW2VDcvnaeiEA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="PassiveName" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="mWlBNA9+dEuZi0nPECMg8w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [PassiveNameTable].[ID], [PassiveNameTable].[PassiveName] FROM PassiveNameTable; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="PassiveType" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="tIhG92GpdU+yvTNoGhhC7Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1800"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [PassiveTypeTable].[ID], [PassiveTypeTable].[PassiveType] FROM PassiveTypeTable; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Desc" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="4AXp3odpU0abwYiOkyB0eQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DeltaHP" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="VtwvOED7+kywaRskFVcLjg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="DeltaDamage" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="IwsZwmL6yk2DI3GKELQliw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="DeltaDef" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="L5PK7evdjUC0j1PABLnCxg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="DeltaGold" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="6/+NeYcy1Ue1FW31LnR0VA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="DeltaHunger" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="e0p1XnLNlECZq1BMWyJuQg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Count" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="3DqoJorxDEymnglJ0mQ4JQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/ReincarnationInAnotherWorld/ReincarnationProject/Assets/Resources/TextAssets/PassiveTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="PassiveTable.xsd" generated="2017-05-25T17:35:11">
<PassiveTable>
<ID>1</ID>
<PassiveName>1</PassiveName>
<PassiveType>1</PassiveType>
<Desc>축복</Desc>
<DeltaHP>1</DeltaHP>
<DeltaDamage>1</DeltaDamage>
<DeltaDef>1</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>10</Count>
</PassiveTable>
<PassiveTable>
<ID>2</ID>
<PassiveName>2</PassiveName>
<PassiveType>1</PassiveType>
<Desc>상처</Desc>
<DeltaHP>-1</DeltaHP>
<DeltaDamage>-1</DeltaDamage>
<DeltaDef>-1</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>5</Count>
</PassiveTable>
<PassiveTable>
<ID>3</ID>
<PassiveName>3</PassiveName>
<PassiveType>2</PassiveType>
<Desc>검</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>3</DeltaDamage>
<DeltaDef>0</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>5</Count>
</PassiveTable>
<PassiveTable>
<ID>4</ID>
<PassiveName>4</PassiveName>
<PassiveType>2</PassiveType>
<Desc>갑옷</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>0</DeltaDamage>
<DeltaDef>3</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>5</Count>
</PassiveTable>
<PassiveTable>
<ID>5</ID>
<PassiveName>5</PassiveName>
<PassiveType>3</PassiveType>
<Desc>힐링포션</Desc>
<DeltaHP>10</DeltaHP>
<DeltaDamage>0</DeltaDamage>
<DeltaDef>0</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>1</Count>
</PassiveTable>
<PassiveTable>
<ID>6</ID>
<PassiveName>6</PassiveName>
<PassiveType>3</PassiveType>
<Desc>빵</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>0</DeltaDamage>
<DeltaDef>0</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>-10</DeltaHunger>
<Count>1</Count>
</PassiveTable>
<PassiveTable>
<ID>7</ID>
<PassiveName>7</PassiveName>
<PassiveType>4</PassiveType>
<Desc>코볼트고기</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>0</DeltaDamage>
<DeltaDef>0</DeltaDef>
<DeltaGold>20</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>1</Count>
</PassiveTable>
<PassiveTable>
<ID>8</ID>
<PassiveName>8</PassiveName>
<PassiveType>4</PassiveType>
<Desc>트롤고기</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>0</DeltaDamage>
<DeltaDef>0</DeltaDef>
<DeltaGold>100</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>1</Count>
</PassiveTable>
<PassiveTable>
<ID>9</ID>
<PassiveName>9</PassiveName>
<PassiveType>1</PassiveType>
<Desc>공포</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>-5</DeltaDamage>
<DeltaDef>-2</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>5</Count>
</PassiveTable>
<PassiveTable>
<ID>10</ID>
<PassiveName>10</PassiveName>
<PassiveType>2</PassiveType>
<Desc>브로드소드</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>5</DeltaDamage>
<DeltaDef>1</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>5</Count>
</PassiveTable>
<PassiveTable>
<ID>11</ID>
<PassiveName>11</PassiveName>
<PassiveType>2</PassiveType>
<Desc>체인매일</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>0</DeltaDamage>
<DeltaDef>5</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>5</Count>
</PassiveTable>
<PassiveTable>
<ID>12</ID>
<PassiveName>12</PassiveName>
<PassiveType>4</PassiveType>
<Desc>코볼트 피</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>0</DeltaDamage>
<DeltaDef>0</DeltaDef>
<DeltaGold>10</DeltaGold>
<DeltaHunger>0</DeltaHunger>
<Count>1</Count>
</PassiveTable>
<PassiveTable>
<ID>13</ID>
<PassiveName>13</PassiveName>
<PassiveType>3</PassiveType>
<Desc>신선한 물</Desc>
<DeltaHP>0</DeltaHP>
<DeltaDamage>0</DeltaDamage>
<DeltaDef>0</DeltaDef>
<DeltaGold>0</DeltaGold>
<DeltaHunger>-5</DeltaHunger>
<Count>0</Count>
</PassiveTable>
</dataroot>
